jobs:
- job: demo
  displayName: MyDemo
  pool:
    vmImage: 'ubuntu-latest'
  steps:
  - task: oc-cmd@2
    inputs: 
      connectionType: 'OpenShift Connection Service'
      openshiftService: 'azuredevops'
      cmd: 'status'
  - task: oc-cmd@2
    inputs:
      openshiftService: 'azuredevops'
      cmd: 'oc new-project simon'
      uselocalOc: true
  - task: oc-cmd@2
    inputs:
      openshiftService: 'azuredevops'
      cmd: 'oc start-build nodejs-ex --follow'
      uselocalOc: true
  - task: oc-cmd@2
    inputs:
      openshiftService: 'azuredevops'
      cmd: 'oc status'
      uselocalOc: true
